// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCybRnj3uDhXERSz9THZd2GxX2Cnimo0lo',
    appId: '1:505000605506:web:25ff4917bd52fa9a35badb',
    messagingSenderId: '505000605506',
    projectId: 'musicalapp-96621',
    authDomain: 'musicalapp-96621.firebaseapp.com',
    storageBucket: 'musicalapp-96621.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnDDPERUSLKhYY_4AuPhroOUXdO_kHVMc',
    appId: '1:505000605506:android:00a140957ce6e02435badb',
    messagingSenderId: '505000605506',
    projectId: 'musicalapp-96621',
    storageBucket: 'musicalapp-96621.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiuoWQGb30zZDd8RNLUl5Iar4oZ6lwLkY',
    appId: '1:505000605506:ios:54e5e9a3eb372d3235badb',
    messagingSenderId: '505000605506',
    projectId: 'musicalapp-96621',
    storageBucket: 'musicalapp-96621.appspot.com',
    iosBundleId: 'com.example.musicalapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiuoWQGb30zZDd8RNLUl5Iar4oZ6lwLkY',
    appId: '1:505000605506:ios:21a7297d3bcbffb235badb',
    messagingSenderId: '505000605506',
    projectId: 'musicalapp-96621',
    storageBucket: 'musicalapp-96621.appspot.com',
    iosBundleId: 'com.example.musicalapp.RunnerTests',
  );
}
